tools:
  # Runs PHP Code Sniffer
  php_code_sniffer:
    filter:
      extensions:
        - php
      excluded_paths:
        - example
        - tests
      standard:
        - Zend

  # Runs PHP Copy/Paste Detector
  php_cpd:
    command: phpcpd

    # A list of excluded directories.
    excluded_dirs:
      - example
      - tests

  # Runs the PHP Mess Detector (http://phpmd.org).
  php_mess_detector: true

  # Analyzes the size and structure of a PHP project.
  php_pdepend:
    command: pdepend
    configuration_file: ~
    suffixes:
      - php
    excluded_dirs:
      - example
      - tests
            
  php_analyzer: true
    
  external_code_coverage: true
  
  # Collects code coverage information about the changeset.
  #php_code_coverage:
  #  test_command:  phpunit
  #  config_path:  ~