language: php

php: 
  - 5.3
  - 5.4

before_script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - php -l class.simple_mail.php

script:
  - phpunit --configuration ./tests/stub.xml
  - phpcs --standard=PSR1 class.simple_mail.php
